# Generated by Django 6.0.5 on 2026-05-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='', max_length=50)),
                ('pro_price', models.IntegerField(default='', max_length=25)),
                ('pro_qauntity', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
